CI: actually run with Cygwin Python
Cygwin was installed but the regular Python interpreter was actually
used to run the test. Fix this. Also merge Cygwin tests setup
definition with the one for other environments.

The Python distributed by Cygwin is broken and requires some peculiar
maneuvers to make it suitable to create virtual environments. Address
that in the CI configuration.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -61,6 +61,89 @@ jobs:
           env_vars: PYTHON
           name: ${{ matrix.python }}
 
+  cygwin:
+    runs-on: windows-latest
+    env:
+      FORCE_COLOR: true
+    strategy:
+      fail-fast: false
+      matrix:
+        python:
+          - '3.9'
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Setup Cygwin
+        uses: cygwin/cygwin-install-action@v2
+        with:
+          packages: >-
+            python39
+            python39-devel
+            python39-pip
+            python39-setuptools
+            cmake
+            gcc-core
+            gcc-g++
+            git
+            make
+            ninja
+
+      - name: Fix git dubious ownership
+        # This addresses the "fatal: detected dubious ownership in
+        # repository" and "fatal: not in a git directory" errors
+        # encountered when trying to run Cygwin git in a directory not
+        # owned by the current user. This happens when the tests run
+        # Cygwin git in a directory outside the Cygwin filesystem.
+        run: git config --global --add safe.directory '*'
+        shell: C:\cygwin\bin\env.exe CYGWIN_NOWINPATH=1 CHERE_INVOKING=1 C:\cygwin\bin\bash.exe -leo pipefail -o igncr {0}
+
+      - name: Get pip cache path
+        id: pip-cache-path
+        run: echo "path=$(cygpath -w $(python -m pip cache dir))" >> $GITHUB_OUTPUT
+        shell: C:\cygwin\bin\env.exe CYGWIN_NOWINPATH=1 CHERE_INVOKING=1 C:\cygwin\bin\bash.exe -leo pipefail -o igncr {0}
+
+      - name: Restore cache
+        # Cygwin Python cannot use binary wheels from PyPI. Building
+        # some dependencies takes considerable time. Caching the built
+        # wheels speeds up the CI job quite a bit.
+        uses: actions/cache@v3
+        with:
+          path: ${{ steps.pip-cache-path.outputs.path }}
+          key: cygwin-pip-${{ github.sha }}
+          restore-keys: cygwin-pip-
+
+      - name: Install
+        # Cygwin patches Python's ensurepip module to look for the
+        # wheels needed to initialize a new virtual environment in
+        # /usr/share/python-wheels/ but nothing in Cygwin actually
+        # puts the setuptools and pip wheels there. Fix this.
+        run: |
+          mkdir /usr/share/python-wheels/
+          pushd /usr/share/python-wheels/
+          python -m pip --disable-pip-version-check download setuptools pip
+          popd
+          python -m pip --disable-pip-version-check install .[test]
+        shell: C:\cygwin\bin\env.exe CYGWIN_NOWINPATH=1 CHERE_INVOKING=1 C:\cygwin\bin\bash.exe -leo pipefail -o igncr {0}
+
+      - name: Run tests
+        run: >-
+          python -m pytest --showlocals -vv --cov
+          --cov-config setup.cfg
+          --cov-report=xml:coverage-${{ matrix.python }}.xml
+        shell: C:\cygwin\bin\env.exe CYGWIN_NOWINPATH=1 CHERE_INVOKING=1 C:\cygwin\bin\bash.exe -leo pipefail -o igncr {0}
+
+      - name: Send coverage report
+        uses: codecov/codecov-action@v1
+        if: ${{ always() }}
+        env:
+          PYTHON: cygwin-${{ matrix.python }}
+        with:
+          flags: tests
+          env_vars: PYTHON
+          name: cygwin-${{ matrix.python }}
+
   pyston:
     runs-on: ubuntu-20.04
     env:
